# Exported from Render on 2025-06-16T22:40:13Z
services:
- type: web
  name: Drsfan
  runtime: docker
  repo: https://github.com/trongnp0706/Drsfan
  branch: feature/deploysetting
  plan: free
  envVars:
  - key: ASPNETCORE_URLS
    sync: false
  - key: ASPNETCORE_ENVIRONMENT
    sync: false
  region: singapore
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
  buildFilter:
    paths:
    - DrsfanWebApp
    - Drsfan.DataAccess
    - Drsfan.Models
    - Drsfan.Utility
    ignoredPaths:
    - .git
    - .vs
    - bin
    - obj
version: "1"
