// <auto-generated />
using System;
using Drsfan.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Drsfan.DataAccess.Migrations
{
    [DbContext(typeof(DrsfanDbContext))]
    partial class DrsfanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Drsfan.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Washing Machines"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Refrigerators"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Air Conditioners"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Microwave Ovens"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Vacuum Cleaners"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Water Purifiers"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Dishwashers"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Electric Kettles"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Coffee Makers"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Rice Cookers"
                        });
                });

            modelBuilder.Entity("Drsfan.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Appliance Way",
                            City = "New York",
                            Name = "Home Essentials Ltd.",
                            PhoneNumber = "212-555-7890",
                            PostalCode = "10001",
                            State = "NY"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Gourmet Ave",
                            City = "Los Angeles",
                            Name = "KitchenPro Inc.",
                            PhoneNumber = "310-555-1234",
                            PostalCode = "90001",
                            State = "CA"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Lifestyle Blvd",
                            City = "Chicago",
                            Name = "Modern Living Solutions",
                            PhoneNumber = "312-555-5678",
                            PostalCode = "60601",
                            State = "IL"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Smart Home St",
                            City = "San Francisco",
                            Name = "Tech & Comfort Co.",
                            PhoneNumber = "415-555-8765",
                            PostalCode = "94101",
                            State = "CA"
                        });
                });

            modelBuilder.Entity("Drsfan.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Drsfan.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Carrier")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("text");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PaymentDueDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("Drsfan.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DiscountPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ListPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PowerConsumption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WarrantyPeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Samsung",
                            CategoryId = 1,
                            Description = "The Samsung EcoBubble Washer offers powerful cleaning with its unique EcoBubble technology, which transforms detergent into bubbles for faster penetration into fabrics. It ensures effective cleaning even at low temperatures, saving energy while protecting delicate clothing.",
                            DiscountPrice = 399.99000000000001,
                            Features = "Hygiene Steam, Digital Inverter, EcoBubble Technology",
                            ListPrice = 450.0,
                            ModelNumber = "WW70J3280KW",
                            Name = "Samsung EcoBubble Front Load Washer",
                            PowerConsumption = "200W",
                            WarrantyPeriod = "2 years"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "LG",
                            CategoryId = 1,
                            Description = "Designed for ultimate convenience, the LG Smart Inverter Washer delivers low noise and high energy efficiency. Its TurboDrum technology ensures powerful washing, while the Smart Diagnosis feature allows you to troubleshoot issues directly from your smartphone.",
                            DiscountPrice = 449.99000000000001,
                            Features = "TurboDrum, Smart Diagnosis, Smart Inverter Control",
                            ListPrice = 500.0,
                            ModelNumber = "T80SJMB1Z",
                            Name = "LG Smart Inverter Top Load Washer",
                            PowerConsumption = "250W",
                            WarrantyPeriod = "3 years"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Samsung",
                            CategoryId = 2,
                            Description = "This spacious Samsung refrigerator features a frost-free design and a digital inverter compressor for long-lasting cooling. The Twin Cooling technology maintains optimal humidity levels, keeping fruits and vegetables fresh for longer periods.",
                            DiscountPrice = 549.99000000000001,
                            Features = "Twin Cooling, MoistFresh Zone, Power Freeze",
                            ListPrice = 600.0,
                            ModelNumber = "RT30T3722S8",
                            Name = "Samsung Double Door Refrigerator",
                            PowerConsumption = "350W",
                            WarrantyPeriod = "3 years"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Whirlpool",
                            CategoryId = 2,
                            Description = "The Whirlpool Multi-Door Refrigerator offers advanced cooling technology, ensuring every corner of the fridge maintains a consistent temperature. Its Zeolite Technology absorbs excess moisture, preventing fruits and vegetables from getting soggy.",
                            DiscountPrice = 649.99000000000001,
                            Features = "Zeolite Technology, FreshFlow Air Tower, Adaptive Intelligence",
                            ListPrice = 699.99000000000001,
                            ModelNumber = "IF INV CNV 515",
                            Name = "Whirlpool Multi-Door Refrigerator",
                            PowerConsumption = "400W",
                            WarrantyPeriod = "3 years"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Daikin",
                            CategoryId = 3,
                            Description = "The Daikin Split Air Conditioner combines sleek design with high performance. Its PM2.5 air filter ensures cleaner air indoors, while its energy-efficient inverter technology reduces electricity bills. Perfect for all weather conditions.",
                            DiscountPrice = 649.99000000000001,
                            Features = "PM2.5 Filter, Quiet Operation, High-Efficiency Cooling",
                            ListPrice = 700.0,
                            ModelNumber = "FTKF50TV",
                            Name = "Daikin Split AC with Inverter Technology",
                            PowerConsumption = "1500W",
                            WarrantyPeriod = "5 years"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "LG",
                            CategoryId = 3,
                            Description = "With Dual Inverter Compressor technology, the LG DualCool Split AC ensures faster and quieter cooling. It features Monsoon Comfort for humid weather and an Anti-Bacterial Filter for improved air quality.",
                            DiscountPrice = 699.99000000000001,
                            Features = "Anti-Bacterial Filter, Dual Inverter, Monsoon Comfort",
                            ListPrice = 750.0,
                            ModelNumber = "KS-Q18SNZD",
                            Name = "LG DualCool Split AC",
                            PowerConsumption = "1450W",
                            WarrantyPeriod = "10 years"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Panasonic",
                            CategoryId = 4,
                            Description = "The Panasonic Convection Microwave Oven offers versatile cooking options, from grilling to baking. Its sleek design fits perfectly into modern kitchens, while the Auto Cook menu simplifies the preparation of your favorite dishes.",
                            DiscountPrice = 179.99000000000001,
                            Features = "Convection Cooking, Auto Cook Menu, Touch Keypad",
                            ListPrice = 200.0,
                            ModelNumber = "NN-CT645BFDG",
                            Name = "Panasonic Convection Microwave Oven",
                            PowerConsumption = "1200W",
                            WarrantyPeriod = "2 years"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Samsung",
                            CategoryId = 4,
                            Description = "Compact and easy to use, the Samsung Solo Microwave Oven is perfect for reheating, defrosting, and simple cooking. Its ceramic enamel cavity ensures easy cleaning and durability.",
                            DiscountPrice = 129.99000000000001,
                            Features = "Ceramic Enamel Cavity, Quick Defrost, Reheat Function",
                            ListPrice = 150.0,
                            ModelNumber = "MS23J5133AG",
                            Name = "Samsung Solo Microwave Oven",
                            PowerConsumption = "1150W",
                            WarrantyPeriod = "1 year"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Dyson",
                            CategoryId = 5,
                            Description = "Experience powerful suction and unmatched convenience with the Dyson V11 Cordless Vacuum Cleaner. It offers multiple cleaning modes and a long battery life, making it ideal for homes with pets and children.",
                            DiscountPrice = 850.0,
                            Features = "HEPA Filtration, Cordless Design, Multiple Cleaning Modes",
                            ListPrice = 900.0,
                            ModelNumber = "V11 Absolute Pro",
                            Name = "Dyson V11 Cordless Vacuum Cleaner",
                            PowerConsumption = "545W",
                            WarrantyPeriod = "2 years"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Philips",
                            CategoryId = 5,
                            Description = "Keep your home spotless with the Philips Bagless Vacuum Cleaner. Its PowerCyclone 5 technology delivers high suction efficiency, and the ergonomic design ensures easy handling.",
                            DiscountPrice = 180.0,
                            Features = "Bagless, PowerCyclone 5, Advanced Dust Bin Design",
                            ListPrice = 200.0,
                            ModelNumber = "FC9352/01",
                            Name = "Philips Bagless Vacuum Cleaner",
                            PowerConsumption = "1900W",
                            WarrantyPeriod = "2 years"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Bosch",
                            CategoryId = 6,
                            Description = "The Bosch Freestanding Dishwasher is a powerful kitchen appliance, designed to save time and water while providing superior cleaning. With multiple wash programs and a sleek design, it's perfect for modern homes.",
                            DiscountPrice = 650.0,
                            Features = "EcoSilence Drive, AquaStop, Load Sensor",
                            ListPrice = 700.0,
                            ModelNumber = "SMS46KI03I",
                            Name = "Bosch Freestanding Dishwasher",
                            PowerConsumption = "1200W",
                            WarrantyPeriod = "2 years"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "IFB",
                            CategoryId = 6,
                            Description = "The IFB Neptune VX Dishwasher offers an energy-efficient and noise-free cleaning experience. Its Jet Wash program ensures quick cleaning in just 18 minutes, making it ideal for busy households.",
                            DiscountPrice = 580.0,
                            Features = "Jet Wash, Adjustable Racks, EcoWash Mode",
                            ListPrice = 600.0,
                            ModelNumber = "Neptune VX",
                            Name = "IFB Neptune VX Dishwasher",
                            PowerConsumption = "1100W",
                            WarrantyPeriod = "2 years"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "De'Longhi",
                            CategoryId = 7,
                            Description = "Enjoy barista-quality coffee at home with the De'Longhi Espresso Coffee Machine. It features a 15-bar pressure system and a manual frother for creamy cappuccinos and lattes.",
                            DiscountPrice = 350.0,
                            Features = "15-bar Pump, Manual Frother, Compact Design",
                            ListPrice = 400.0,
                            ModelNumber = "EC685.R",
                            Name = "De'Longhi Espresso Coffee Machine",
                            PowerConsumption = "1450W",
                            WarrantyPeriod = "1 year"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Nespresso",
                            CategoryId = 7,
                            Description = "The Nespresso Vertuo Plus offers convenience and versatility, allowing you to brew a variety of coffee sizes. Its Centrifusion technology ensures optimal flavor extraction with every cup.",
                            DiscountPrice = 220.0,
                            Features = "Centrifusion Technology, One-Touch Brewing, Large Water Tank",
                            ListPrice = 250.0,
                            ModelNumber = "GCA1-US-BM-NE",
                            Name = "Nespresso Vertuo Plus Coffee Maker",
                            PowerConsumption = "1350W",
                            WarrantyPeriod = "1 year"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Philips",
                            CategoryId = 8,
                            Description = "Boil water in minutes with the Philips Electric Kettle. It features a stainless steel design, 1.5-liter capacity, and an automatic shut-off function for safety.",
                            DiscountPrice = 35.0,
                            Features = "Stainless Steel, 1.5L Capacity, Automatic Shut-Off",
                            ListPrice = 40.0,
                            ModelNumber = "HD9306/06",
                            Name = "Philips Electric Kettle",
                            PowerConsumption = "2000W",
                            WarrantyPeriod = "1 year"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Morphy Richards",
                            CategoryId = 8,
                            Description = "The Morphy Richards InstaCook Electric Kettle is perfect for boiling water, making instant noodles, or preparing beverages. Its cool-touch handle ensures safe operation.",
                            DiscountPrice = 45.0,
                            Features = "Multi-Purpose, Cool-Touch Handle, 1L Capacity",
                            ListPrice = 50.0,
                            ModelNumber = "Instacook",
                            Name = "Morphy Richards InstaCook Kettle",
                            PowerConsumption = "1800W",
                            WarrantyPeriod = "1 year"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Cuisinart",
                            CategoryId = 9,
                            Description = "The Cuisinart Food Processor simplifies meal preparation with its large 14-cup capacity and multiple blade attachments. It's perfect for chopping, slicing, and kneading dough.",
                            DiscountPrice = 230.0,
                            Features = "14-Cup Capacity, Stainless Steel Blades, Easy-to-Clean Design",
                            ListPrice = 250.0,
                            ModelNumber = "DFP-14BCNY",
                            Name = "Cuisinart 14-Cup Food Processor",
                            PowerConsumption = "1000W",
                            WarrantyPeriod = "3 years"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Philips",
                            CategoryId = 9,
                            Description = "Compact yet powerful, the Philips Daily Collection Food Processor offers efficient food preparation with multiple accessories for slicing, chopping, and blending.",
                            DiscountPrice = 90.0,
                            Features = "Compact Design, Multiple Accessories, Easy Storage",
                            ListPrice = 100.0,
                            ModelNumber = "HR7627/00",
                            Name = "Philips Daily Collection Food Processor",
                            PowerConsumption = "700W",
                            WarrantyPeriod = "2 years"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "NutriBullet",
                            CategoryId = 10,
                            Description = "The NutriBullet Pro is a compact yet powerful blender designed to extract nutrients from fruits and vegetables. It's perfect for making smoothies, sauces, and more.",
                            DiscountPrice = 130.0,
                            Features = "Powerful Motor, Easy to Clean, Compact Design",
                            ListPrice = 150.0,
                            ModelNumber = "NB9-1301",
                            Name = "NutriBullet Pro Blender",
                            PowerConsumption = "900W",
                            WarrantyPeriod = "1 year"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Vitamix",
                            CategoryId = 10,
                            Description = "The Vitamix Explorian Blender offers exceptional versatility with 10-speed settings and a powerful motor. Its durable design ensures long-lasting performance for both hot and cold blends.",
                            DiscountPrice = 330.0,
                            Features = "10-Speed Settings, Self-Cleaning, Durable Construction",
                            ListPrice = 350.0,
                            ModelNumber = "E310",
                            Name = "Vitamix Explorian Blender",
                            PowerConsumption = "1400W",
                            WarrantyPeriod = "3 years"
                        });
                });

            modelBuilder.Entity("Drsfan.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Drsfan.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Drsfan.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("text");

                    b.HasIndex("CompanyId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Drsfan.Models.OrderDetail", b =>
                {
                    b.HasOne("Drsfan.Models.OrderHeader", "OrderHeader")
                        .WithMany()
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drsfan.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Drsfan.Models.OrderHeader", b =>
                {
                    b.HasOne("Drsfan.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Drsfan.Models.Product", b =>
                {
                    b.HasOne("Drsfan.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Drsfan.Models.ProductImage", b =>
                {
                    b.HasOne("Drsfan.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Drsfan.Models.ShoppingCart", b =>
                {
                    b.HasOne("Drsfan.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drsfan.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Drsfan.Models.ApplicationUser", b =>
                {
                    b.HasOne("Drsfan.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Drsfan.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
